source 'https://rubygems.org'
gem 'capistrano', '~> 3.7'
# gem 'capistrano-magento2'
gem 'capistrano-magento2', :github => 'davidalger/capistrano-magento2', :branch => 'feature/zero-down-deployment'
gem 'terminal-notifier'
